const fakeData = [
  {
    productName: "Laptop",
    productPrice: "$1200",
    costPrice: "$1000",
    sellingPrice: "$1250",
    description: "High-performance laptop",
    availableStock: 50,
    unitSold: 200,
    action: "Edit/Delete",
  },
  {
    productName: "Smartphone",
    productPrice: "$800",
    costPrice: "$650",
    sellingPrice: "$850",
    description: "Latest model smartphone",
    availableStock: 30,
    unitSold: 150,
    action: "Edit/Delete",
  },
  {
    productName: "Headphones",
    productPrice: "$150",
    costPrice: "$100",
    sellingPrice: "$180",
    description: "Wireless noise-cancelling headphones",
    availableStock: 100,
    unitSold: 300,
    action: "Edit/Delete",
  },
  {
    productName: "Monitor",
    productPrice: "$300",
    costPrice: "$250",
    sellingPrice: "$320",
    description: "24-inch Full HD monitor",
    availableStock: 20,
    unitSold: 50,
    action: "Edit/Delete",
  },
  {
    productName: "Keyboard",
    productPrice: "$50",
    costPrice: "$30",
    sellingPrice: "$60",
    description: "Mechanical keyboard",
    availableStock: 80,
    unitSold: 120,
    action: "Edit/Delete",
  },
  {
    productName: "Mouse",
    productPrice: "$40",
    costPrice: "$25",
    sellingPrice: "$50",
    description: "Ergonomic wireless mouse",
    availableStock: 90,
    unitSold: 140,
    action: "Edit/Delete",
  },
  {
    productName: "Printer",
    productPrice: "$200",
    costPrice: "$150",
    sellingPrice: "$220",
    description: "High-quality color printer",
    availableStock: 15,
    unitSold: 25,
    action: "Edit/Delete",
  },
  {
    productName: "Tablet",
    productPrice: "$500",
    costPrice: "$400",
    sellingPrice: "$550",
    description: "10-inch tablet with stylus",
    availableStock: 40,
    unitSold: 70,
    action: "Edit/Delete",
  },
  {
    productName: "Webcam",
    productPrice: "$100",
    costPrice: "$80",
    sellingPrice: "$120",
    description: "1080p HD webcam",
    availableStock: 60,
    unitSold: 100,
    action: "Edit/Delete",
  },
  {
    productName: "Speakers",
    productPrice: "$120",
    costPrice: "$90",
    sellingPrice: "$130",
    description: "Bluetooth stereo speakers",
    availableStock: 70,
    unitSold: 85,
    action: "Edit/Delete",
  },
];

export { fakeData };
